#!/usr/bin/env node
/**
 * Tests for VerilogSymbolVisitor warning conditions.
 *
 * Covers Warning 1 through Warning 12 as generated by _generateWarnings()
 * and _finalizeWarnings() in src/antlr-parser.ts:
 *
 *  1. Signal referenced but not declared
 *  2. Signal declared but never used
 *  3. Assign statement l-value is a reg
 *  4. Procedural assignment l-value is a wire
 *  5. Input signal used as l-value
 *  6. Output/inout port of instantiated module connected to reg signal
 *  7. Signal is never assigned
 *  8. Missing port in named port connection
 *  9. Instantiated module not found in module database
 * 10. Bit width mismatch between l-value and expression
 * 11. Condition expression has width > 1 bit
 * 12. Bit width mismatch between connected signal and instantiated module port
 */

// Set up VS Code mock before requiring any source files
(global as any).vscode = {
    DiagnosticSeverity: { Error: 0, Warning: 1, Information: 2, Hint: 3 }
};

const SEVERITY_WARNING = 1;

const AntlrVerilogParser = require('../src/antlr-parser');
const { ModuleDatabase } = require('../src/database');

// ── Simple test harness ────────────────────────────────────────────────────

let passed = 0;
let failed = 0;

function assert(condition: boolean, message: string): void {
    if (condition) {
        console.log(`  ✓ ${message}`);
        passed++;
    } else {
        console.error(`  ✗ ${message}`);
        failed++;
    }
}

// ── Helpers ────────────────────────────────────────────────────────────────

/** Create a mock TextDocument from inline Verilog source text. */
function makeInlineDoc(text: string, name: string) {
    return {
        getText: () => text,
        uri: { toString: () => `file:///test/${name}` }
    };
}

/** Parse inline Verilog and return the warning diagnostics. */
function getWarnings(verilog: string, name: string, db?: any): any[] {
    const parser = new AntlrVerilogParser();
    const moduleDb = db ?? new ModuleDatabase();
    parser.parseSymbols(makeInlineDoc(verilog, name), moduleDb, null);
    parser.dirty();
    parser.parseSymbols(makeInlineDoc(verilog, name), moduleDb, null);
    const diags = parser.getDiagnostics(moduleDb);
    return diags.filter((d: any) => d.severity === SEVERITY_WARNING);
}

// ── Warning 1: signal referenced but not declared ─────────────────────────

console.log('\nWarning 1: signal referenced but not declared');
{
    const verilog = `
module warn1(input wire clk, output wire out);
  assign out = undeclared_sig;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn1.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'undeclared_sig'") && w.message.includes('not declared'));
    assert(w !== undefined, "warning for 'undeclared_sig' is referenced but not declared");
}

// ── Warning 2: signal declared but never used ─────────────────────────────

console.log('\nWarning 2: signal declared but never used');
{
    const verilog = `
module warn2(input wire clk, output reg out);
  wire never_used;
  always @(posedge clk) out <= clk;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn2.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'never_used'") && w.message.includes('never used'));
    assert(w !== undefined, "warning for 'never_used' is declared but never used");
}

// ── Warning 3: assign statement l-value is a reg ──────────────────────────

console.log('\nWarning 3: assign statement l-value is a reg');
{
    const verilog = `
module warn3(input wire clk, output wire out);
  reg my_reg;
  assign my_reg = clk;
  assign out = my_reg;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn3.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'my_reg'") && w.message.includes('reg'));
    assert(w !== undefined, "warning for assign l-value 'my_reg' is a reg");
}

// ── Warning 4: procedural assignment l-value is a wire ────────────────────

console.log('\nWarning 4: procedural assignment l-value is a wire');
{
    const verilog = `
module warn4(input wire clk, output reg out);
  wire my_wire;
  always @(posedge clk) begin
    my_wire <= clk;
    out <= my_wire;
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn4.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'my_wire'") && w.message.includes('wire'));
    assert(w !== undefined, "warning for procedural l-value 'my_wire' is a wire");
}

// ── Warning 5: input signal used as l-value ───────────────────────────────

console.log('\nWarning 5: input signal used as l-value');
{
    const verilog = `
module warn5(input wire clk, output reg out);
  always @(posedge clk) begin
    clk <= 1'b0;
    out <= 1'b1;
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn5.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'clk'") && w.message.includes('cannot be used as l-value'));
    assert(w !== undefined, "warning for input 'clk' used as l-value");
}

// ── Warning 6: output port of instantiation connected to reg ─────────────

console.log('\nWarning 6: output port of instantiation connected to reg');
{
    const verilog = `
module submod6(output wire driven_out);
  assign driven_out = 1'b0;
endmodule

module warn6(input wire clk, output wire out);
  reg my_reg;
  submod6 inst(.driven_out(my_reg));
  assign out = my_reg;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn6.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'my_reg'") &&
        w.message.includes("output port") &&
        w.message.includes("cannot be connected to reg"));
    assert(w !== undefined,
        "warning for output port 'driven_out' connected to reg 'my_reg'");
}

// ── Warning 7: signal is never assigned ───────────────────────────────────

console.log('\nWarning 7: signal is never assigned');
{
    const verilog = `
module warn7(input wire clk, output wire out);
  wire never_assigned;
  assign out = never_assigned;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn7.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'never_assigned'") && w.message.includes('never assigned'));
    assert(w !== undefined, "warning for 'never_assigned' is never assigned");
}

// ── Warning 8: missing port in named port connection ──────────────────────

console.log('\nWarning 8: missing port in named port connection');
{
    const verilog = `
module submod8(input wire a, input wire b, output wire c);
  assign c = a & b;
endmodule

module warn8(input wire clk, input wire data, output wire result);
  submod8 inst(.a(clk), .c(result));
endmodule
`;
    const warnings = getWarnings(verilog, 'warn8.v');
    const w = warnings.find((w: any) => w.message.includes("'b' unconnected"));
    assert(w !== undefined, "warning for missing port 'b' in named port connection");
}

// ── Warning 9: instantiated module not found in module database ───────────

console.log('\nWarning 9: instantiated module not found in database');
{
    const verilog = `
module warn9(input wire clk, output wire out);
  nonexistent_mod inst(.clk(clk), .out(out));
endmodule
`;
    const db = new ModuleDatabase();
    const warnings = getWarnings(verilog, 'warn9.v', db);
    const w = warnings.find((w: any) =>
        w.message.includes("'nonexistent_mod'") && w.message.includes('not defined'));
    assert(w !== undefined, "warning for instantiated module 'nonexistent_mod' not defined");
}

// ── Warning 10: bit width mismatch between l-value and expression ──────────

console.log('\nWarning 10: bit width mismatch between l-value and expression');
{
    const verilog = `
module warn10(input wire clk, output reg [3:0] out);
  always @(posedge clk) begin
    out <= 8'hFF;
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn10.v');
    const w = warnings.find((w: any) =>
        w.message.includes("Bit width mismatch") &&
        w.message.includes("'out'") &&
        w.message.includes('width 4') &&
        w.message.includes('width 8'));
    assert(w !== undefined,
        "warning for bit width mismatch: 'out' has width 4 but expression has width 8");
}

// ── Warning 11: condition expression has width > 1 bit ────────────────────

console.log('\nWarning 11: condition expression has width > 1 bit');
{
    const verilog = `
module warn11(input wire clk, input wire [7:0] data, output reg out);
  always @(posedge clk) begin
    if (data) begin
      out <= 1'b1;
    end else begin
      out <= 1'b0;
    end
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn11.v');
    const w = warnings.find((w: any) =>
        w.message.includes('Condition expression') &&
        w.message.includes('width 8') &&
        w.message.includes('condition should be 1-bit'));
    assert(w !== undefined,
        "warning for condition expression 'data' (8 bits) in if statement");
}

// ── Warning 12: bit width mismatch between signal and module port ──────────

console.log('\nWarning 12: bit width mismatch between connected signal and module port');
{
    const verilog = `
module submod12(input wire [7:0] wide_in, output wire out);
  assign out = wide_in[0];
endmodule

module warn12(input wire [3:0] narrow, output wire result);
  submod12 inst(.wide_in(narrow), .out(result));
endmodule
`;
    const warnings = getWarnings(verilog, 'warn12.v');
    const w = warnings.find((w: any) =>
        w.message.includes("Port 'wide_in'") &&
        w.message.includes('width 8') &&
        w.message.includes("'narrow'") &&
        w.message.includes('width 4'));
    assert(w !== undefined,
        "warning for 4-bit 'narrow' connected to 8-bit port 'wide_in'");
}

// ── Summary ────────────────────────────────────────────────────────────────

console.log(`\nResults: ${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
