#!/usr/bin/env node
/**
 * Tests for VerilogSymbolVisitor warning conditions.
 *
 * Covers Warning 1 through Warning 12 as generated by _generateWarnings()
 * and _finalizeWarnings() in src/antlr-parser.ts:
 *
 *  1. Signal referenced but not declared
 *  2. Signal declared but never used
 *  3. Assign statement l-value is a reg
 *  4. Procedural assignment l-value is a wire
 *  5. Input signal used as l-value
 *  6. Output/inout port of instantiated module connected to reg signal
 *  7. Signal is never assigned
 *  8. Missing port in named port connection
 *  9. Instantiated module not found in module database
 * 10. Bit width mismatch between l-value and expression
 * 11. Condition expression has width > 1 bit
 * 12. Bit width mismatch between connected signal and instantiated module port
 */

// Set up VS Code mock before requiring any source files
(global as any).vscode = {
    DiagnosticSeverity: { Error: 0, Warning: 1, Information: 2, Hint: 3 }
};

const SEVERITY_WARNING = 1;

import * as fs from 'fs';
import * as path from 'path';

const AntlrVerilogParser = require('../src/verilog-parser');
const { ModuleDatabase } = require('../src/database');

const contentsDir = path.join(__dirname, '..', 'contents', 'verilog');

// ── Simple test harness ────────────────────────────────────────────────────

let passed = 0;
let failed = 0;

function assert(condition: boolean, message: string): void {
    if (condition) {
        console.log(`  ✓ ${message}`);
        passed++;
    } else {
        console.error(`  ✗ ${message}`);
        failed++;
    }
}

// ── Helpers ────────────────────────────────────────────────────────────────

/** Create a mock TextDocument from inline Verilog source text. */
function makeInlineDoc(text: string, name: string) {
    return {
        getText: () => text,
        uri: { toString: () => `file:///test/${name}` }
    };
}

/** Create a mock TextDocument from a file in the contents directory. */
function makeFileDoc(filename: string) {
    const text = fs.readFileSync(path.join(contentsDir, filename), 'utf8');
    return {
        getText: () => text,
        uri: { toString: () => `file://${path.join(contentsDir, filename)}` }
    };
}

/** Parse a Verilog file from the contents directory and return the warning diagnostics. */
function getFileWarnings(filename: string, db?: any): any[] {
    const parser = new AntlrVerilogParser();
    const moduleDb = db ?? new ModuleDatabase();
    parser.parseSymbols(makeFileDoc(filename), moduleDb, null);
    const diags = parser.getDiagnostics(moduleDb);
    return diags.filter((d: any) => d.severity === SEVERITY_WARNING);
}

/** Parse inline Verilog and return the warning diagnostics. */
function getWarnings(verilog: string, name: string, db?: any): any[] {
    const parser = new AntlrVerilogParser();
    const moduleDb = db ?? new ModuleDatabase();
    //parser.parseSymbols(makeInlineDoc(verilog, name), moduleDb, null);
    //parser.dirty();
    parser.parseSymbols(makeInlineDoc(verilog, name), moduleDb, null);
    const diags = parser.getDiagnostics(moduleDb);
    return diags.filter((d: any) => d.severity === SEVERITY_WARNING);
}

// ── Warning 1: signal referenced but not declared ─────────────────────────

console.log('\nWarning 1: signal referenced but not declared');
{
    const verilog = `
module submod1(input wire a, input wire b, output wire c);
  assign c = a & b;
endmodule

module warn1(input wire clk, output wire out);
  assign out = undeclared_sig1;

  submod1 inst1(.a(clk), .b(undeclared_sig2) .c(result));
  submod1 inst2(.a(clk), .b({clk,undeclared_sig3}) .c(result));
endmodule
`;
    const warnings = getWarnings(verilog, 'warn1.v');
    const w1 = warnings.find((w: any) =>
        w.message.includes("'undeclared_sig1'") && w.message.includes('not declared'));
    assert(w1 !== undefined, "warning for 'undeclared_sig1' is referenced but not declared");
    const w2 = warnings.find((w: any) =>
        w.message.includes("'undeclared_sig2'") && w.message.includes('not declared'));
    assert(w2 !== undefined, "warning for 'undeclared_sig2' is referenced but not declared");
    const w3 = warnings.find((w: any) =>
        w.message.includes("'undeclared_sig3'") && w.message.includes('not declared'));
    assert(w3 !== undefined, "warning for 'undeclared_sig3' is referenced but not declared");
}

// ── Warning 2: signal declared but never used ─────────────────────────────

console.log('\nWarning 2: signal declared but never used');
{
    const verilog = `
module warn2(input wire clk, output reg out);
  wire never_used;
  always @(posedge clk) out <= clk;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn2.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'never_used'") && w.message.includes('never used'));
    assert(w !== undefined, "warning for 'never_used' is declared but never used");
}

// ── Warning 3: assign statement l-value is a reg ──────────────────────────

console.log('\nWarning 3: assign statement l-value is a reg');
{
    const verilog = `
module warn3(input wire clk, output wire out);
  reg my_reg;
  assign my_reg = clk;
  assign out = my_reg;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn3.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'my_reg'") && w.message.includes('reg'));
    assert(w !== undefined, "warning for assign l-value 'my_reg' is a reg");
}

// ── Warning 4: procedural assignment l-value is a wire ────────────────────

console.log('\nWarning 4: procedural assignment l-value is a wire');
{
    const verilog = `
module warn4(input wire clk, output reg out);
  wire my_wire;
  always @(posedge clk) begin
    my_wire <= clk;
    out <= my_wire;
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn4.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'my_wire'") && w.message.includes('wire'));
    assert(w !== undefined, "warning for procedural l-value 'my_wire' is a wire");
}

// ── Warning 5: input signal used as l-value ───────────────────────────────

console.log('\nWarning 5: input signal used as l-value');
{
    const verilog = `
module warn5(input wire clk, output reg out);
  always @(posedge clk) begin
    clk <= 1'b0;
    out <= 1'b1;
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn5.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'clk'") && w.message.includes('cannot be used as l-value'));
    assert(w !== undefined, "warning for input 'clk' used as l-value");
}

// ── Warning 6: output port of instantiation connected to reg ─────────────

console.log('\nWarning 6: output port of instantiation connected to reg');
{
    const verilog = `
module submod6(output wire driven_out);
  assign driven_out = 1'b0;
endmodule

module warn6(input wire clk, output wire out);
  reg my_reg;
  submod6 inst(.driven_out(my_reg));
  assign out = my_reg;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn6.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'my_reg'") &&
        w.message.includes("output port") &&
        w.message.includes("cannot be connected to reg"));
    assert(w !== undefined,
        "warning for output port 'driven_out' connected to reg 'my_reg'");
}

// ── Warning 7: signal is never assigned ───────────────────────────────────

console.log('\nWarning 7: signal is never assigned');
{
    const verilog = `
module warn7(input wire clk, output wire out);
  wire never_assigned;
  assign out = never_assigned;
endmodule
`;
    const warnings = getWarnings(verilog, 'warn7.v');
    const w = warnings.find((w: any) =>
        w.message.includes("'never_assigned'") && w.message.includes('never assigned'));
    assert(w !== undefined, "warning for 'never_assigned' is never assigned");
}

// ── Warning 8: missing port in named port connection ──────────────────────

console.log('\nWarning 8: missing port in named port connection');
{
    const verilog = `
module submod8(input wire a, input wire b, output wire c);
  assign c = a & b;
endmodule

module warn8(input wire clk, input wire data, output wire result);
  submod8 inst(.a(clk), .c(result));
endmodule
`;
    const warnings = getWarnings(verilog, 'warn8.v');
    const w = warnings.find((w: any) => w.message.includes("'b' unconnected"));
    assert(w !== undefined, "warning for missing port 'b' in named port connection");
}

// ── Warning 9: instantiated module not found in module database ───────────

console.log('\nWarning 9: instantiated module not found in database');
{
    const verilog = `
module warn9(input wire clk, output wire out);
  nonexistent_mod inst(.clk(clk), .out(out));
endmodule
`;
    const db = new ModuleDatabase();
    const warnings = getWarnings(verilog, 'warn9.v', db);
    const w = warnings.find((w: any) =>
        w.message.includes("'nonexistent_mod'") && w.message.includes('not defined'));
    assert(w !== undefined, "warning for instantiated module 'nonexistent_mod' not defined");
}

// ── Warning 10: bit width mismatch between l-value and expression ──────────

console.log('\nWarning 10: bit width mismatch between l-value and expression');
{
    const verilog = `
module warn10(input wire clk, output reg [3:0] out);
  always @(posedge clk) begin
    out <= 8'hFF;
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn10.v');
    const w = warnings.find((w: any) =>
        w.message.includes("Bit width mismatch") &&
        w.message.includes("'out'") &&
        w.message.includes('width 4') &&
        w.message.includes('width 8'));
    assert(w !== undefined,
        "warning for bit width mismatch: 'out' has width 4 but expression has width 8");
}

// ── Warning 11: condition expression has width > 1 bit ────────────────────

console.log('\nWarning 11: condition expression has width > 1 bit');
{
    const verilog = `
module warn11(input wire clk, input wire [7:0] data, output reg out);
  always @(posedge clk) begin
    if (data) begin
      out <= 1'b1;
    end else begin
      out <= 1'b0;
    end
  end
endmodule
`;
    const warnings = getWarnings(verilog, 'warn11.v');
    const w = warnings.find((w: any) =>
        w.message.includes('Condition expression') &&
        w.message.includes('width 8') &&
        w.message.includes('condition should be 1-bit'));
    assert(w !== undefined,
        "warning for condition expression 'data' (8 bits) in if statement");
}

// ── Warning 12: bit width mismatch between signal and module port ──────────

console.log('\nWarning 12: bit width mismatch between connected signal and module port');
{
    const verilog = `
module submod12(input wire [7:0] wide_in, output wire out);
  assign out = wide_in[0];
endmodule

module warn12(input wire [3:0] narrow, output wire result);
  submod12 inst(.wide_in(narrow), .out(result));
endmodule
`;
    const warnings = getWarnings(verilog, 'warn12.v');
    const w = warnings.find((w: any) =>
        w.message.includes("Port 'wide_in'") &&
        w.message.includes('width 8') &&
        w.message.includes("'narrow'") &&
        w.message.includes('width 4'));
    assert(w !== undefined,
        "warning for 4-bit 'narrow' connected to 8-bit port 'wide_in'");
}

// ── test_generate.v: genvar variable i should not warn, j should warn ─────

console.log('\ntest_generate.v: genvar i should not warn, undeclared j should warn');
{
    const warnings = getFileWarnings('test_generate.v');
    const warnI = warnings.find((w: any) =>
        w.message.includes("'i'") && w.message.includes('not declared'));
    assert(warnI === undefined,
        "no warning for genvar 'i' used inside generate block");

    const warnJ = warnings.find((w: any) =>
        w.message.includes("'j'") && w.message.includes('not declared'));
    assert(warnJ !== undefined,
        "warning for undeclared 'j' used inside generate block");
}

// ── test_instance.v: addr port bit width with parameterized ram module ─────
// ram module is defined before test_instance so that it is available in the
// database when the instantiation's port widths are evaluated.

console.log('\ntest_instance.v: addr port bit width in ram instantiation');
{
    const verilog = `
module ram #(
    parameter DEPTH = 32,
    parameter WIDTH = 8,
    parameter ADR_WIDTH = (DEPTH == 16) ? 4 : (DEPTH == 32) ? 5 : (DEPTH == 64) ? 6 : 0
)
(
    input clk,
    input[ADR_WIDTH-1:0] addr,
    input [WIDTH-1:0] data_in,
    input we,
    input re,
    output reg [WIDTH-1:0] data_out
);
reg[WIDTH-1:0] mem[0:DEPTH-1];
always @(posedge clk) begin
    if (we) begin
        mem[addr] <= data_in;
    end else if (re) begin
        data_out <= mem[addr];
    end
end
endmodule

module test_instance (
    input clk,
    output reg[7:0] count_out
);
reg[4:0] addr;
wire[7:0] data_out_1, data_out_2;

always @(posedge clk) begin
    count_out <= data_out_1 ^ data_out_2;
    addr <= addr + 1;
end

ram #(
    .DEPTH(16),
    .WIDTH(8)
) ram_i_1 (
    .clk(clk),
    .we(1'b0),
    .re(1'b1),
    .addr(addr),
    .data_in(8'h00),
    .data_out(data_out_1)
);

ram #(
    .DEPTH(32),
    .WIDTH(8)
) ram_i_2 (
    .clk(clk),
    .we(1'b0),
    .re(1'b1),
    .addr(addr),
    .data_in(8'h00),
    .data_out(data_out_2)
);
endmodule
`;
    const warnings = getWarnings(verilog, 'test_instance_inline.v');

    // ram_i_1: DEPTH=16 → ADR_WIDTH=4 → addr port is 4 bits, but addr signal is 5 bits
    const warnRam1 = warnings.find((w: any) =>
        w.message.includes("Port 'addr'") &&
        w.message.includes('width 4') &&
        w.message.includes("'addr'") &&
        w.message.includes('width 5'));
    assert(warnRam1 !== undefined,
        "warning for 5-bit 'addr' signal connected to 4-bit 'addr' port in ram_i_1 (DEPTH=16)");

    // ram_i_2: DEPTH=32 → ADR_WIDTH=5 → addr port is 5 bits and addr signal is 5 bits → no warning
    const warnRam2 = warnings.find((w: any) =>
        w.message.includes("Port 'addr' has width 5,"));
    assert(warnRam2 === undefined,
        "no bit-width warning for 5-bit 'addr' signal connected to 5-bit 'addr' port in ram_i_2 (DEPTH=32)");
}

// ── test_instance.v ram_i_3: scalar port widths and bit-select expressions ──
// Regression tests for the port-width bug where scalar (1-bit) ports/signals
// were reported with width null instead of width 1.

console.log('\ntest_instance.v ram_i_3: scalar port / bit-select width evaluation');
{
    const verilog = `
module ram #(
    parameter DEPTH = 32,
    parameter WIDTH = 8,
    parameter ADR_WIDTH = (DEPTH == 16) ? 4 : (DEPTH == 32) ? 5 : (DEPTH == 64) ? 6 : 0
)
(
    input clk,
    input[ADR_WIDTH-1:0] addr,
    input [WIDTH-1:0] data_in,
    input we,
    input re,
    output reg [WIDTH-1:0] data_out
);
reg[WIDTH-1:0] mem[0:DEPTH-1];
always @(posedge clk) begin
    if (we) begin
        mem[addr] <= data_in;
    end else if (re) begin
        data_out <= mem[addr];
    end
end
endmodule

module test_instance (
    input clk,
    input reset,
    output reg[7:0] count_out
);
reg[4:0] addr;
reg[3:0] init_h, init_l;
wire[3:0] count_h, count_l;
always @(posedge clk) begin
    count_out <= {count_h, count_l};
    addr <= addr + 1;
end

ram #(
    .DEPTH(32),
    .WIDTH(8)
) ram_i_3 (
    .clk(clk),
    .re(addr[0]),
    .we(addr[1]),
    .addr(reset),
    .data_in({init_h, init_l}),
    .data_out({count_h, count_l})
);
endmodule
`;
    const warnings = getWarnings(verilog, 'test_instance_ram_i3.v');

    // re and we ports are 1-bit scalars; addr[0] and addr[1] are 1-bit bit-selects.
    // There must be no width-mismatch warning for re or we.
    const warnRe = warnings.find((w: any) =>
        w.message.includes("Port 're'"));
    assert(warnRe === undefined,
        "no width warning for 1-bit 're' port connected to 1-bit addr[0] bit-select");

    const warnWe = warnings.find((w: any) =>
        w.message.includes("Port 'we'"));
    assert(warnWe === undefined,
        "no width warning for 1-bit 'we' port connected to 1-bit addr[1] bit-select");

    // addr port is ADR_WIDTH (5) bits wide; reset is a 1-bit scalar input.
    // The warning must report reset's width as 1, not null.
    const warnAddr = warnings.find((w: any) =>
        w.message.includes("Port 'addr'") &&
        w.message.includes('width 5') &&
        w.message.includes("'reset'") &&
        w.message.includes('width 1'));
    assert(warnAddr !== undefined,
        "warning for 1-bit 'reset' signal connected to 5-bit 'addr' port (width shown as 1, not null)");
}

// ── Part-select bit width evaluation: signal[hi:lo] and {a, b[hi:lo]} ──────
// Regression test for bug where range_expression [hi:lo] (parsed as
// msb_constant_expression ':' lsb_constant_expression in the new ANTLR grammar)
// was mis-evaluated as 1 bit because rangeExprCtx.expression() returned 0 items.

console.log('\nPart-select width evaluation: signal[hi:lo] and concatenation with [hi:lo]');
{
    const verilog = `
module sub(
    input [2:0] aport,
    input [7:0] dport,
    output out
);
endmodule

module top(output out);
reg [4:0] addr;
reg [3:0] init_h, init_l;
sub inst(
    .aport(addr[2:0]),
    .dport({init_h, init_l[3:0]}),
    .out(out)
);
endmodule
`;
    const warnings = getWarnings(verilog, 'test_part_select_width.v');

    // addr[2:0] should be 3 bits → matches 3-bit 'aport' → no width warning
    const warnAport = warnings.find((w: any) => w.message.includes("Port 'aport'"));
    assert(warnAport === undefined,
        "no width warning for 3-bit 'aport' port connected to addr[2:0] (part-select = 3 bits)");

    // {init_h[3:0]=4bits, init_l[3:0]=4bits} = 8 bits → matches 8-bit 'dport' → no width warning
    const warnDport = warnings.find((w: any) => w.message.includes("Port 'dport'"));
    assert(warnDport === undefined,
        "no width warning for 8-bit 'dport' port connected to {init_h, init_l[3:0]} (concat = 8 bits)");
}

// ── Indexed part-select bit width evaluation: signal[base+:width] / [base-:width] ──
// Regression test for bug where [base +: width] was evaluated as width=1 because
// rangeExprCtx.expression() returns null for the new grammar's base_expression '+:'
// width_constant_expression alternative.

console.log('\nIndexed part-select (+: / -:) width evaluation');
{
    const verilog = `
module sub(
    input [4:0] a5port,
    input [3:0] a4port,
    output out
);
endmodule

module top(output out);
reg [4:0] addr;
sub inst(
    .a5port(addr[0+:5]),
    .a4port(addr[1-:4]),
    .out(out)
);
endmodule
`;
    const warnings = getWarnings(verilog, 'test_indexed_part_select_width.v');

    // addr[0+:5] → width 5 → matches 5-bit 'a5port' → no width warning
    const warnA5 = warnings.find((w: any) => w.message.includes("Port 'a5port'"));
    assert(warnA5 === undefined,
        "no width warning for 5-bit 'a5port' connected to addr[0+:5] (indexed part-select = 5 bits)");

    // addr[1-:4] → width 4 → matches 4-bit 'a4port' → no width warning
    const warnA4 = warnings.find((w: any) => w.message.includes("Port 'a4port'"));
    assert(warnA4 === undefined,
        "no width warning for 4-bit 'a4port' connected to addr[1-:4] (indexed part-select = 4 bits)");
}

// ── Summary ────────────────────────────────────────────────────────────────

console.log(`\nResults: ${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
